### ISSUE TITLE
Post 1.0 Roadmap

### ISSUE THREAD

**Issue by DominicParent** [StatCan/tass-ssat#160]
This issue is to be used to discuss our plan for a post 1.0 roadmap. The main description here will contain a list of tasks/features/objectives, which may spawn attached issues.

Other discussion points (processes, procedures, etc) are welcome as well in the comments.

- [ ] Create an orchestrator.
  - [ ] Orchestrator configuration file needs to be created.
  - [ ] Support running tests from multiple tass-base config files.
  - [ ] Support convert-test-report workflow (as well as other tass modules).
- [ ] Create installation/deployment script for all tass modules.
- [ ] Update documentation.

**Comment by DominicParent** [comment]
@Pswenne @ty-desj comments? Suggestions?

**Comment by DominicParent** [comment]
Updated comment with notes from whiteboard brainstorm meeting.
